services:
  backend:
    image: dsmcar-api
    container_name: dsmcar-api
    build:
      context: .
    ports:
      - '8080:8080'
    env_file: .env
    volumes:
      - .:/usr/src/app/api
    depends_on:
      - database
  database:
    image: postgres:17.2-alpine3.20
    container_name: dsmcardb
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'

    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
  redis:
    image: redis:8.2-m01-alpine
    container_name: dsmcar-redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - '6379:6379'

volumes:
  pgdata:

networks:
  default:
    name: dsmcar-app
